// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_scaffold/test/services/distribution_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i5;

import 'package:flutter_scaffold/src/utils/file_utils.dart' as _i3;
import 'package:flutter_scaffold/src/utils/process_utils.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProcessResult_0 extends _i1.SmartFake implements _i2.ProcessResult {
  _FakeProcessResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FileUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileUtils extends _i1.Mock implements _i3.FileUtils {
  MockFileUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentDirectory =>
      (super.noSuchMethod(
            Invocation.getter(#currentDirectory),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currentDirectory),
            ),
          )
          as String);

  @override
  bool directoryExists(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#directoryExists, [path]),
            returnValue: false,
          )
          as bool);

  @override
  bool fileExists(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#fileExists, [path]),
            returnValue: false,
          )
          as bool);

  @override
  bool createDirectory(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#createDirectory, [path]),
            returnValue: false,
          )
          as bool);

  @override
  bool createFile(String? path, String? content, {bool? force = false}) =>
      (super.noSuchMethod(
            Invocation.method(#createFile, [path, content], {#force: force}),
            returnValue: false,
          )
          as bool);

  @override
  void deleteDirectory(String? path) => super.noSuchMethod(
    Invocation.method(#deleteDirectory, [path]),
    returnValueForMissingStub: null,
  );

  @override
  String readFile(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#readFile, [path]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#readFile, [path]),
            ),
          )
          as String);

  @override
  void writeFile(String? path, String? content) => super.noSuchMethod(
    Invocation.method(#writeFile, [path, content]),
    returnValueForMissingStub: null,
  );

  @override
  void deleteFile(String? path) => super.noSuchMethod(
    Invocation.method(#deleteFile, [path]),
    returnValueForMissingStub: null,
  );

  @override
  void copyFile(String? source, String? destination) => super.noSuchMethod(
    Invocation.method(#copyFile, [source, destination]),
    returnValueForMissingStub: null,
  );

  @override
  void makeExecutable(String? path) => super.noSuchMethod(
    Invocation.method(#makeExecutable, [path]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.FileSystemEntity> listFiles(
    String? path, {
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listFiles, [path], {#recursive: recursive}),
            returnValue: <_i5.FileSystemEntity>[],
          )
          as List<_i5.FileSystemEntity>);

  @override
  int countFiles(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#countFiles, [path]),
            returnValue: 0,
          )
          as int);

  @override
  int countDirectories(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#countDirectories, [path]),
            returnValue: 0,
          )
          as int);

  @override
  List<String> listSubdirectories(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#listSubdirectories, [path]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  String joinPath(
    String? part1, [
    String? part2,
    String? part3,
    String? part4,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#joinPath, [part1, part2, part3, part4]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#joinPath, [part1, part2, part3, part4]),
            ),
          )
          as String);

  @override
  String dirname(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#dirname, [path]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#dirname, [path]),
            ),
          )
          as String);

  @override
  String basename(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#basename, [path]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#basename, [path]),
            ),
          )
          as String);

  @override
  String normalize(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#normalize, [path]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#normalize, [path]),
            ),
          )
          as String);

  @override
  bool isFlutterProject(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#isFlutterProject, [path]),
            returnValue: false,
          )
          as bool);

  @override
  String? getProjectName(String? projectPath) =>
      (super.noSuchMethod(Invocation.method(#getProjectName, [projectPath]))
          as String?);

  @override
  String getDirectorySize(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getDirectorySize, [path]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getDirectorySize, [path]),
            ),
          )
          as String);
}

/// A class which mocks [ProcessUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockProcessUtils extends _i1.Mock implements _i2.ProcessUtils {
  MockProcessUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ProcessResult> run(
    String? executable,
    List<String>? arguments, {
    String? workingDirectory,
    bool? showOutput = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #run,
              [executable, arguments],
              {#workingDirectory: workingDirectory, #showOutput: showOutput},
            ),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(
                  #run,
                  [executable, arguments],
                  {
                    #workingDirectory: workingDirectory,
                    #showOutput: showOutput,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);

  @override
  _i6.Future<_i2.ProcessResult> runOrThrow(
    String? executable,
    List<String>? arguments, {
    String? workingDirectory,
    bool? showOutput = true,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runOrThrow,
              [executable, arguments],
              {
                #workingDirectory: workingDirectory,
                #showOutput: showOutput,
                #errorMessage: errorMessage,
              },
            ),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(
                  #runOrThrow,
                  [executable, arguments],
                  {
                    #workingDirectory: workingDirectory,
                    #showOutput: showOutput,
                    #errorMessage: errorMessage,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);

  @override
  _i6.Future<_i2.ProcessResult> flutter(
    List<String>? arguments, {
    String? workingDirectory,
    bool? showOutput = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #flutter,
              [arguments],
              {#workingDirectory: workingDirectory, #showOutput: showOutput},
            ),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(
                  #flutter,
                  [arguments],
                  {
                    #workingDirectory: workingDirectory,
                    #showOutput: showOutput,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);

  @override
  _i6.Future<_i2.ProcessResult> dart(
    List<String>? arguments, {
    String? workingDirectory,
    bool? showOutput = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #dart,
              [arguments],
              {#workingDirectory: workingDirectory, #showOutput: showOutput},
            ),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(
                  #dart,
                  [arguments],
                  {
                    #workingDirectory: workingDirectory,
                    #showOutput: showOutput,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);

  @override
  _i6.Future<_i2.ProcessResult> pubAdd(
    List<String>? packages, {
    String? workingDirectory,
    bool? isDev = false,
    bool? showOutput = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pubAdd,
              [packages],
              {
                #workingDirectory: workingDirectory,
                #isDev: isDev,
                #showOutput: showOutput,
              },
            ),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(
                  #pubAdd,
                  [packages],
                  {
                    #workingDirectory: workingDirectory,
                    #isDev: isDev,
                    #showOutput: showOutput,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);

  @override
  _i6.Future<_i2.ProcessResult> pubGet({
    String? workingDirectory,
    bool? showOutput = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pubGet, [], {
              #workingDirectory: workingDirectory,
              #showOutput: showOutput,
            }),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(#pubGet, [], {
                  #workingDirectory: workingDirectory,
                  #showOutput: showOutput,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);

  @override
  _i6.Future<_i2.ProcessResult> buildRunner({
    String? workingDirectory,
    bool? deleteConflicting = true,
    bool? showOutput = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildRunner, [], {
              #workingDirectory: workingDirectory,
              #deleteConflicting: deleteConflicting,
              #showOutput: showOutput,
            }),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(#buildRunner, [], {
                  #workingDirectory: workingDirectory,
                  #deleteConflicting: deleteConflicting,
                  #showOutput: showOutput,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);

  @override
  _i6.Future<_i2.ProcessResult> analyze({
    String? workingDirectory,
    bool? showOutput = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyze, [], {
              #workingDirectory: workingDirectory,
              #showOutput: showOutput,
            }),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(#analyze, [], {
                  #workingDirectory: workingDirectory,
                  #showOutput: showOutput,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);

  @override
  _i6.Future<_i2.ProcessResult> createProject(
    String? projectPath, {
    String? org,
    String? description,
    List<String>? platforms,
    List<String>? extraArgs = const [],
    bool? showOutput = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createProject,
              [projectPath],
              {
                #org: org,
                #description: description,
                #platforms: platforms,
                #extraArgs: extraArgs,
                #showOutput: showOutput,
              },
            ),
            returnValue: _i6.Future<_i2.ProcessResult>.value(
              _FakeProcessResult_0(
                this,
                Invocation.method(
                  #createProject,
                  [projectPath],
                  {
                    #org: org,
                    #description: description,
                    #platforms: platforms,
                    #extraArgs: extraArgs,
                    #showOutput: showOutput,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.ProcessResult>);
}
